name: newitem_alarm
description: 프로젝트 먹어봤니

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path_provider: ^2.0.2
  provider: ^6.0.1
  url_launcher: ^6.0.15
  page_view_indicators: ^2.0.0
  youtube_player_flutter: ^8.0.0
  image_picker: ^0.8.4
  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1 #^4.2.0이상부터는 Dark SDK >=2.14.0이어야 함.
  #json 직렬화(serializable)을 위해서.
  tab_indicator_styler: ^2.0.0
  scrolling_page_indicator: ^0.1.3 #이것때문에 null-safety적용이 불가능함...!!
  carousel_slider: ^4.0.0
  favorite_button: ^0.0.4
  animated_splash_screen: ^1.0.1+2
  auto_size_text: ^3.0.0 #범위에 맞게 Text 사이즈 자동으로 조정해주는 것.
  share:
  intl:
  cupertino_date_textbox:
  get: #GetX
  scrollable_positioned_list: ^0.2.3
  cloud_firestore:
  firebase_core:
#  firebase_database:
#  shared_preferences:
#  firebase_messaging:
#  flutter_local_notifications:
#  cached_network_image:
#  image_pickers:
#  image_cropper:
#  photo_view:
#  url_launcher_android:




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^4.1.4 #6.0.0이상부터는 Dark SDK >=2.14.0이어야 함.
  #빌드할 때만 사용되기 때문에 dev_dependencies에


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
